pub mod operations;
pub mod registries;
pub mod parser;
pub mod evaluator;
pub mod lexer;
pub mod core_initializer;
pub mod evaluate_service;
pub mod error_display;
pub mod repl_output;
mod runtime_error;